Feature/bottom up express building
PKWadsy/kint pull request #15
Opened 2024-04-19 01:17 UTC by joshuabrownenz

This PR creates the concept of an AppBuilder.

An App builder takes in the root node of the kint RouteTreeNode and will build a framework-specific app/router. 

Currently, there is only expressAppBuilder defined. However, this could easily be extended. It is also the default from kint.buildRouter. 

The whole process is Typesafe.

I think this serves as a good base to 
-  #2 simplify the process of adding middleware
- #14 move away from depending on express. The express builder could come as a separate package so it has zero cost unless you import it
- #14 Move away from depending on Zod. This PR doesn't included any zod configuration. But I think I similar principle could be used for middleware/zod building.

2024-05-16 04:07 UTC, PKWadsy requested changes
Looks great! Added a few comments to resolve

2024-05-16 04:07 UTC, PKWadsy commented on src/defaultRouterBuilders/expressAppBuilder.ts
> +}
Not sure I like this as opposed to just 
`buildExpressApp(context: Context): Express { ... }`

2024-05-16 04:07 UTC, PKWadsy commented on src/kint.ts
> +import { expressAppBuilder } from "./defaultRouterBuilders/expressAppBuilder";
Quotes changed?

2024-05-16 04:07 UTC, PKWadsy commented on src/kint.ts
>  			RequestBody extends ZodSchemaDefinition,
This is still coupled to express by the `defineExpressEndpoint`. Perhaps it would be better to have a function called `expressKint` which provides a `buildExpressApp` and `defineExpressEndpoint` and then maybe `koaKint` which provides `buildKoaApp` and `defineKoaEndpoint`. Or are you thinking of just having a `defineEndpoint` function down the line instead (i.e. moving away from express all together for our request and response objects)?

2024-05-17 10:55 UTC, joshuabrownenz commented on src/kint.ts
> +import { expressAppBuilder } from "./defaultRouterBuilders/expressAppBuilder";
Prettier auto format... What would you prefer? Cause I can set prettier to use single, double or not change quotes?

2024-05-17 10:57 UTC, joshuabrownenz commented on src/kint.ts
>  			RequestBody extends ZodSchemaDefinition,
Considering our converstation about moving towards a kint request and kint response object. Moving to a `defineEndpoint` function makes a lot of sense.

2024-05-17 11:01 UTC, joshuabrownenz commented on src/models/AppBuilder.ts
> +}
It was just an interface that just provides scafolding for if you want to implement a different type of AppBuilder?
I know we are talking about moving away from pre-built libraries altogether so possibly this becomes unessesary cause we don't support it anymore

2024-05-17 11:01 UTC, joshuabrownenz commented on .prettierrc
> +    "useTabs": true
Yes. That makes sense. When I was editing I saw that you were using tabs and my prettier auto format kept overwriting your code so I was making my formatter match yours. I will change prettierrc to use 2 spaces

2024-05-17 11:04 UTC, joshuabrownenz commented on src/defaultRouterBuilders/expressAppBuilder.ts
> +}
We possibly don't need to go down this route anymore. As discussed offline, we are possibly going to move towards our own HTTP or other protocol library. Meaning we don't maybe don't need to support an AppBuilder archeteicure  like this

2024-05-17 11:06 UTC, joshuabrownenz commented on .prettierrc
> +    "useTabs": true
@PKWadsy Just had a look and the rest of the codebase is using tabs (not sure if your default is tabs). We should probably change all tabs to two spaces in a different PR

2024-05-17 11:07 UTC, joshuabrownenz commented on src/kint.ts
> +import { expressAppBuilder } from "./defaultRouterBuilders/expressAppBuilder";
How strict do we want prettiers formatting for this project?

2024-05-28 10:29 UTC, PKWadsy commented on src/kint.ts
> +import { expressAppBuilder } from "./defaultRouterBuilders/expressAppBuilder";
I think we should setup a pre commit hook and use eslint

2024-06-12 00:10 UTC, joshuabrownenz commented
Closing this for now as #18 is better attempt at fixing the same issues

2024-06-12 00:10 UTC, closed without merging