Route building architecture
PKWadsy/kint pull request #29
Opened 2024-06-15 10:01 UTC by PKWadsy

Significant refactorings to the route tree builder, as described in #28 

The `RouteTreeBuilder` has been split into three modules

1. A route tree module that represents a tree of endpoints.
2. A builder which takes a routes folder and builds an endpoint tree
3. An adapter which converts the endpoint tree to an express router

2024-06-16 03:47 UTC, joshuabrownenz requested changes
I'm requesting a couple more tests. I'm happy to write them in another PR if you want me to try get our coverage numbers up a bit. Maybe just check the es-lint suppresion before merging

2024-06-16 03:47 UTC, joshuabrownenz commented on src/core/createKint.ts
> +    kint: KintEndpointBuilder.new<GlobalContext>(),
I like this distinction in naming

2024-06-16 03:47 UTC, joshuabrownenz commented on src/core/endpoint-builder/KintEndpointBuilder.ts
> +        innerHandler: ConfigurableHandler<NewContext, NewConfig>,
Hey sorry, but I'm a bit lost on what this type assertion does for `innerHandler`? Cause you're not actually doing anything to change the `innerHandler`?

2024-06-16 03:47 UTC, joshuabrownenz commented on src/core/endpoint-builder/KintEndpointBuilder.ts
> +      /**
Is it best practice to create a function like this inside another function? Maybe depth of 1 is ok but lets make sure it doesn't get out of hand

2024-06-16 03:47 UTC, joshuabrownenz commented on src/core/endpoint-builder/extractParts.ts
>    return {
I think you need to add some eslint suppresion here. Unless you can figure out a way to get info info here safely.

2024-06-16 03:47 UTC, joshuabrownenz commented on src/core/endpoint-builder/handlerWithValidators.ts
>  /**
es-lint suppresion for the below as assertions are probably a good ideas as well. (You can't avoid as with a reduce function like that)

2024-06-16 03:47 UTC, joshuabrownenz commented on src/core/endpoint-tree/fs-builder/buildEndpointTreeFromDirectory.ts
> +      throw new Error(
The following two Codecov warnings can easily be addressed by tests. I'm happy to write the tests for you if you want.

2024-06-16 03:47 UTC, joshuabrownenz commented on src/core/endpoint-tree/toExpressRouter.ts
> +          throw new KintResponse(body, status);
Interesting. It seems like none of the tests are actually sending responses. Probably pretty important to test that functionality works.

2024-06-16 03:47 UTC, joshuabrownenz commented on src/core/endpoint-tree/toExpressRouter.ts
> +        response.status(kintResponse.status).send(kintResponse.body);
Once again. It's probably worth running a quick test for your handling of promises in as a response.

2024-06-16 03:47 UTC, joshuabrownenz commented on src/core/endpoint-tree/toExpressRouter.ts
> +  for (const subRoute of endpointTree.subRoutes) {
Sorry for going on about tests. A quick test for nested routes would be a good idea.

2024-06-16 03:48 UTC, joshuabrownenz commented on src/core/endpoint-tree/toExpressRouter.ts
> +          throw new KintResponse(body, status);
i.e. doesn't look like we are actually calling endpoints in our test cases

2024-06-16 08:22 UTC, PKWadsy commented on src/core/endpoint-builder/KintEndpointBuilder.ts
> +        innerHandler: ConfigurableHandler<NewContext, NewConfig>,
I have spent many hours on this. The logic of the program guarantees that by the time that we run this function (the innermost handler builder), the context object and config object will be built up to match the NewContext and NewConfig objects. I can't seem to find a good way around this. Please let me know if you can think of anything.

2024-06-16 08:23 UTC, PKWadsy commented on src/core/endpoint-tree/toExpressRouter.ts
> +          throw new KintResponse(body, status);
Yea this is definitely worth testing for sure

2024-06-16 08:23 UTC, PKWadsy commented on src/core/endpoint-tree/toExpressRouter.ts
> +        response.status(kintResponse.status).send(kintResponse.body);
Agreed

2024-06-16 08:23 UTC, PKWadsy commented on src/core/endpoint-tree/toExpressRouter.ts
> +  for (const subRoute of endpointTree.subRoutes) {
Agreed

2024-06-16 08:24 UTC, PKWadsy commented on src/core/endpoint-tree/fs-builder/buildEndpointTreeFromDirectory.ts
> +      throw new Error(
Yea go for it

2024-06-16 08:26 UTC, PKWadsy commented on src/core/endpoint-builder/KintEndpointBuilder.ts
> +        innerHandler: ConfigurableHandler<NewContext, NewConfig>,
This is the most confusing typescript I have ever written.

2024-06-16 09:48 UTC, joshuabrownenz commented on src/core/endpoint-builder/KintEndpointBuilder.ts
> +        innerHandler: ConfigurableHandler<NewContext, NewConfig>,
Haha lol. Ok at least you can admit that it's confusing. 

When doing this last set of tests I was struggling to grasp what code wraps what code etc. I wonder if there is a nicer we can start to structure everything so it reads slightly better.

2024-06-16 09:49 UTC, joshuabrownenz commented
Closes #7

2024-06-16 10:04 UTC, PKWadsy commented on src/core/endpoint-builder/KintEndpointBuilder.ts
> +      /**
It's not perfect as is. But I think the implementation details can be cleaned up at a later date. I've added a todo for now

2024-06-16 10:04 UTC, PKWadsy commented on src/core/endpoint-builder/extractParts.ts
>    return {
I don't mind leaving the warnings. It leaves the problem open to other contributors to try to make better

2024-06-17 06:06 UTC, joshuabrownenz commented
Ready to merge into develop when you are readu

2024-06-17 06:23 UTC, PKWadsy commented
> Ready to merge into develop when you are ready. @PKWadsy

Need a new approval from ya

2024-06-17 06:58 UTC, joshuabrownenz approved these changes
Good to go!

2024-06-17 06:58 UTC, merged